-   id: ament_lint_cmake_hook
    name: ament_lint_cmake_hook
    description: Check CMake code style using cmakelint.
    language: system
    entry: ament_lint_cmake_hook
    types: [cmake]
    stages: [pre-commit, pre-push, manual]
