-   id: ament_lint_cmake_hook
    name: ament_lint_cmake_hook
    description: Check CMake code style using cmakelint.
    language: system
    entry: ament_lint_cmake_hook
    types: [cmake]

-   id: ament_cpplint_hook
    name: ament_cpplint_hook
    description: Code style checking using cpplint.
    language: system
    entry: ament_cpplint_hook
    types: [c++]

-   id: ament_uncrustify_hook
    name: ament_uncrustify_hook
    description: Code style checking using uncrustify.
    language: system
    entry: ament_uncrustify_hook
    types: [c++]

-   id: ament_xmllint_hook
    name: ament_xmllint_hook
    description: Check XML markup using xmllint.
    language: system
    entry: ament_xmllint_hook
    types: [xml]

-   id: ament_flake8_hook
    name: ament_flake8_hook
    description: Check Python code style using flake8.
    language: system
    entry: ament_flake8_hook
    types: [python]
