-   id: ament_lint_cmake_hook
    name: ament_lint_cmake_hook
    description: Check CMake code style using cmakelint.
    language: system
    entry: ament_lint_cmake_hook
    types: [cmake]

-   id: ament_cpplint_hook
    name: ament_cpplint_hook
    description: Code style checking using cpplint.
    language: system
    entry: ament_cpplint_hook
    types: [c++]
