-   id: ament_lint_cmake
    name: ament_lint_cmake
    description: Check CMake code style using cmakelint.
    language: python
    entry: ament_lint_cmake
    types: [cmake]

-   id: ament_cpplint
    name: ament_cpplint
    description: Code style checking using cpplint.
    language: python
    entry: ament_cpplint
    types: [c++]

-   id: ament_uncrustify
    name: ament_uncrustify
    description: Code style checking using uncrustify.
    language: python
    entry: ament_uncrustify
    types: [c++]

-   id: ament_xmllint
    name: ament_xmllint
    description: Check XML markup using xmllint.
    language: python
    entry: ament_xmllint
    types: [xml]

-   id: ament_flake8
    name: ament_flake8
    description: Check Python code style using flake8.
    language: python
    entry: ament_flake8
    types: [python]

-   id: ament_pep257
    name: ament_pep257
    description: Check Python code style using pep257.
    language: python
    entry: ament_pep257
    types: [python]

-   id: ament_mypy
    name: ament_mypy
    description: Check Python code style using mypy.
    language: python
    entry: ament_mypy
    types: [python]
